// <auto-generated>
// This file was generated by CKli v0.0.8--0183-dev.
// Do not edit this file manually. Changes will be lost when the file is regenerated.
//
// To regenerate: use 'ckli plugin info --compile-mode Debug' (or Release).
// To force recompilation without changing mode: use 'ckli plugin info --force'.
// Alternatively, delete this file and run 'ckli plugin info'.
// </auto-generated>

using CKli.Core;
using CK.Core;
using System;
using System.CodeDom.Compiler;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace CKli.Plugins;

[GeneratedCode("CKli", "0.0.8--0183-dev")]
public static class CompiledPlugins
{
    static ReadOnlySpan<byte> _configSignature => [211,62,171,226,161,88,216,13,219,96,12,24,217,98,210,185,84,225,242,227];

    public static IPluginFactory Get( PluginCollectorContext ctx )
    {
        return _configSignature.SequenceEqual( ctx.Signature ) ? UncheckedGet() : null;
    }

    public static IPluginFactory UncheckedGet()
    {
        var infos = new PluginInfo[]{
            new PluginInfo( "CKli.BranchModel.Plugin", "BranchModel", (PluginStatus)0, null, new IPluginTypeInfo[1] ),
            new PluginInfo( "CKli.VersionTag.Plugin", "VersionTag", (PluginStatus)0, null, new IPluginTypeInfo[1] ),
            new PluginInfo( "CKli.Build.Plugin", "Build", (PluginStatus)0, null, new IPluginTypeInfo[2] ),
            new PluginInfo( "CKli.ReleaseDatabase.Plugin", "ReleaseDatabase", (PluginStatus)0, null, new IPluginTypeInfo[1] ),
            new PluginInfo( "CKli.ArtifactHandler.Plugin", "ArtifactHandler", (PluginStatus)0, null, new IPluginTypeInfo[1] ),
            new PluginInfo( "CKli.Net8Migration.Plugin", "Net8Migration", (PluginStatus)0, null, new IPluginTypeInfo[1] ),
            new PluginInfo( "CKli.ShallowSolution.Plugin", "ShallowSolution", (PluginStatus)0, null, new IPluginTypeInfo[1] ),
        };
        PluginInfo plugin;
        IPluginTypeInfo[] types;
        plugin = infos[0];
        types = (IPluginTypeInfo[])plugin.PluginTypes;
        types[0] = new PluginTypeInfo( plugin, "CKli.BranchModel.Plugin.BranchModelPlugin", true, 0, 4 );
        plugin = infos[1];
        types = (IPluginTypeInfo[])plugin.PluginTypes;
        types[0] = new PluginTypeInfo( plugin, "CKli.VersionTag.Plugin.VersionTagPlugin", true, 0, 2 );
        plugin = infos[2];
        types = (IPluginTypeInfo[])plugin.PluginTypes;
        types[0] = new PluginTypeInfo( plugin, "CKli.Build.Plugin.RepositoryBuilderPlugin", true, 0, 5 );
        types[1] = new PluginTypeInfo( plugin, "CKli.Build.Plugin.BuildPlugin", true, 0, 6 );
        plugin = infos[3];
        types = (IPluginTypeInfo[])plugin.PluginTypes;
        types[0] = new PluginTypeInfo( plugin, "CKli.ReleaseDatabase.Plugin.ReleaseDatabasePlugin", true, 0, 1 );
        plugin = infos[4];
        types = (IPluginTypeInfo[])plugin.PluginTypes;
        types[0] = new PluginTypeInfo( plugin, "CKli.ArtifactHandler.Plugin.ArtifactHandlerPlugin", true, 0, 0 );
        plugin = infos[5];
        types = (IPluginTypeInfo[])plugin.PluginTypes;
        types[0] = new PluginTypeInfo( plugin, "CKli.Net8Migration.Plugin.Net8MigrationPlugin", true, 0, 7 );
        plugin = infos[6];
        types = (IPluginTypeInfo[])plugin.PluginTypes;
        types[0] = new PluginTypeInfo( plugin, "CKli.ShallowSolution.Plugin.ShallowSolutionPlugin", true, 0, 3 );
        var pluginCommands = new PluginCommand[]{
            new Cmd_maintenance＿release_database＿rebuild( infos[1].PluginTypes[0] ),
            new Cmd_fix＿start( infos[0].PluginTypes[0] ),
            new Cmd_fix＿info( infos[0].PluginTypes[0] ),
            new Cmd_fix＿cancel( infos[0].PluginTypes[0] ),
            new Cmd_build( infos[2].PluginTypes[1] ),
            new Cmd_fix＿build( infos[2].PluginTypes[1] ),
            new Cmd_fix＿publish( infos[2].PluginTypes[1] ),
            new Cmd_repo＿rebuild＿old( infos[2].PluginTypes[1] ),
            new Cmd_repo＿rebuild＿version( infos[2].PluginTypes[1] ),
            new Cmd_migrate＿net8( infos[5].PluginTypes[0] ),
        };
        var cmds = new Dictionary<string,Command>();
        foreach( var c in pluginCommands )
        {
            cmds.Add( c.CommandPath, c );
        }
       cmds.Add( "maintenance", null );
       cmds.Add( "maintenance release-database", null );
       cmds.Add( "fix", null );
       cmds.Add( "repo", null );
       cmds.Add( "repo rebuild", null );
       cmds.Add( "migrate", null );
        return new Generated( infos, pluginCommands, CommandNamespace.UnsafeCreate( cmds ) );
    }
}

[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Generated : IPluginFactory
{
    readonly PluginInfo[] _plugins;
    readonly PluginCommand[] _pluginCommands;
    readonly CommandNamespace _commands;

    internal Generated( PluginInfo[] plugins, PluginCommand[] pluginCommands, CommandNamespace commands )
    {
        _plugins = plugins;
        _pluginCommands = pluginCommands;
        _commands = commands;
    }
    
#if DEBUG
    public PluginCompileMode CompileMode => PluginCompileMode.Debug;
#else
    public PluginCompileMode CompileMode => PluginCompileMode.Release;
#endif

    public string GenerateCode() => throw new InvalidOperationException( "CompileMode is not PluginCompileMode.None" );

    public PluginCollection Create( IActivityMonitor monitor, World world )
    {
        var configs = world.DefinitionFile.ReadPluginsConfiguration( monitor );
        Throw.CheckState( "Plugins configurations have already been loaded.", configs != null );
        var objects = new object[8];
        objects[0] = new CKli.ArtifactHandler.Plugin.ArtifactHandlerPlugin( new PrimaryPluginContext( _plugins[4], configs, world ) );
        objects[1] = new CKli.ReleaseDatabase.Plugin.ReleaseDatabasePlugin( new PrimaryPluginContext( _plugins[3], configs, world ), (CKli.ArtifactHandler.Plugin.ArtifactHandlerPlugin)objects[0] );
        objects[2] = new CKli.VersionTag.Plugin.VersionTagPlugin( new PrimaryPluginContext( _plugins[1], configs, world ), (CKli.ReleaseDatabase.Plugin.ReleaseDatabasePlugin)objects[1], (CKli.ArtifactHandler.Plugin.ArtifactHandlerPlugin)objects[0] );
        objects[3] = new CKli.ShallowSolution.Plugin.ShallowSolutionPlugin( new PrimaryPluginContext( _plugins[6], configs, world ) );
        objects[4] = new CKli.BranchModel.Plugin.BranchModelPlugin( new PrimaryPluginContext( _plugins[0], configs, world ), (CKli.VersionTag.Plugin.VersionTagPlugin)objects[2], (CKli.ReleaseDatabase.Plugin.ReleaseDatabasePlugin)objects[1], (CKli.ArtifactHandler.Plugin.ArtifactHandlerPlugin)objects[0], (CKli.ShallowSolution.Plugin.ShallowSolutionPlugin)objects[3] );
        objects[5] = new CKli.Build.Plugin.RepositoryBuilderPlugin( new PrimaryPluginContext( _plugins[2], configs, world ), (CKli.ArtifactHandler.Plugin.ArtifactHandlerPlugin)objects[0] );
        objects[6] = new CKli.Build.Plugin.BuildPlugin( new PrimaryPluginContext( _plugins[2], configs, world ), (CKli.VersionTag.Plugin.VersionTagPlugin)objects[2], (CKli.BranchModel.Plugin.BranchModelPlugin)objects[4], (CKli.Build.Plugin.RepositoryBuilderPlugin)objects[5], (CKli.ReleaseDatabase.Plugin.ReleaseDatabasePlugin)objects[1], (CKli.ArtifactHandler.Plugin.ArtifactHandlerPlugin)objects[0], (CKli.ShallowSolution.Plugin.ShallowSolutionPlugin)objects[3] );
        objects[7] = new CKli.Net8Migration.Plugin.Net8MigrationPlugin( new PrimaryPluginContext( _plugins[5], configs, world ), (CKli.VersionTag.Plugin.VersionTagPlugin)objects[2], (CKli.BranchModel.Plugin.BranchModelPlugin)objects[4], (CKli.Build.Plugin.BuildPlugin)objects[6] );
        return PluginCollectionImpl.CreateAndBindCommands( objects, _plugins, _commands, _pluginCommands );
    }

    public void Dispose() { }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_maintenance＿release_database＿rebuild : PluginCommand
{
    internal Cmd_maintenance＿release_database＿rebuild( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "maintenance release-database rebuild",
                "Suppress the published and local databases and rebuild them from the version tags content.\r\nRemote tags drives the update of the published database and are updated on the remote:\r\na local only version tag will remain local.",
                1,
                -1,
                arguments: [
                ],
                options: [
                ],
                flags: [
                ],
                "RebuildReleaseDatabases", MethodAsyncReturn.None ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return ValueTask.FromResult( ((CKli.VersionTag.Plugin.VersionTagPlugin)Instance).RebuildReleaseDatabases(
                                           monitor, context ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_fix＿start : PluginCommand
{
    internal Cmd_fix＿start( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "fix start",
                "Starts a Fix Workflow. This Repo 'fix/vMajor.Minor' branch is checked out.",
                1,
                -1,
                arguments: [
                    ("version", "The Major or Major.Minor version to fix."),
                ],
                options: [
                ],
                flags: [
                    (["--move-branch",], "Allow 'fix/' branches to be moved on the commit to fix if they are not already on it." ),
                ],
                "FixStartAsync", MethodAsyncReturn.Task ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        var a0 = cmdLine.EatArgument();
        var f0 = cmdLine.EatFlag( Flags[0].Names );
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return new ValueTask<bool>( ((CKli.BranchModel.Plugin.BranchModelPlugin)Instance).FixStartAsync(
                                           monitor, context, a0, f0 ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_fix＿info : PluginCommand
{
    internal Cmd_fix＿info( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "fix info",
                "Dumps the current Fix Workflow.",
                1,
                -1,
                arguments: [
                ],
                options: [
                ],
                flags: [
                ],
                "FixInfo", MethodAsyncReturn.None ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return ValueTask.FromResult( ((CKli.BranchModel.Plugin.BranchModelPlugin)Instance).FixInfo(
                                           monitor, context ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_fix＿cancel : PluginCommand
{
    internal Cmd_fix＿cancel( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "fix cancel",
                "Cancels the current Fix Workflow.",
                1,
                -1,
                arguments: [
                ],
                options: [
                ],
                flags: [
                ],
                "FixCancel", MethodAsyncReturn.None ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return ValueTask.FromResult( ((CKli.BranchModel.Plugin.BranchModelPlugin)Instance).FixCancel(
                                           monitor, context ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_build : PluginCommand
{
    internal Cmd_build( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "build",
                "Build-Test-Package and propagates local packages across the repositories.",
                1,
                -1,
                arguments: [
                ],
                options: [
                    (["--branch",], "Specify the branch to build. By default, the current head is considered.", false ),
                ],
                flags: [
                    (["--all",], "Build all the Repos, not only the ones that consume or produce the current repository." ),
                    (["--skip-tests",], "Don't run tests even if they have never locally run on this commit." ),
                    (["--force-tests",], "Run tests even if they have already run successfully on this commit." ),
                    (["--rebuild",], "Build even if a version tag exists and its artifacts already exist locally." ),
                ],
                "RepoBuild", MethodAsyncReturn.None ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        var o0 = cmdLine.EatSingleOption( Options[0].Names );
        var f0 = cmdLine.EatFlag( Flags[0].Names );
        var f1 = cmdLine.EatFlag( Flags[1].Names );
        var f2 = cmdLine.EatFlag( Flags[2].Names );
        var f3 = cmdLine.EatFlag( Flags[3].Names );
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return ValueTask.FromResult( ((CKli.Build.Plugin.BuildPlugin)Instance).RepoBuild(
                                           monitor, context, o0, f0, f1, f2, f3 ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_fix＿build : PluginCommand
{
    internal Cmd_fix＿build( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "fix build",
                "Local build the current Fix Workflow.",
                1,
                -1,
                arguments: [
                ],
                options: [
                ],
                flags: [
                    (["--skip-tests",], "Don't run tests even if they have never locally run on a commit." ),
                    (["--force-tests",], "Run tests even if they have already run successfully on a commit." ),
                    (["--rebuild",], "Force a rebuild." ),
                ],
                "FixBuildAsync", MethodAsyncReturn.Task ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        var f0 = cmdLine.EatFlag( Flags[0].Names );
        var f1 = cmdLine.EatFlag( Flags[1].Names );
        var f2 = cmdLine.EatFlag( Flags[2].Names );
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return new ValueTask<bool>( ((CKli.Build.Plugin.BuildPlugin)Instance).FixBuildAsync(
                                           monitor, context, f0, f1, f2 ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_fix＿publish : PluginCommand
{
    internal Cmd_fix＿publish( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "fix publish",
                "Local build the current Fix Workflow.",
                1,
                -1,
                arguments: [
                ],
                options: [
                ],
                flags: [
                    (["--rebuild",], "Force a rebuild." ),
                ],
                "FixPublishAsync", MethodAsyncReturn.Task ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        var f0 = cmdLine.EatFlag( Flags[0].Names );
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return new ValueTask<bool>( ((CKli.Build.Plugin.BuildPlugin)Instance).FixPublishAsync(
                                           monitor, context, f0 ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_repo＿rebuild＿old : PluginCommand
{
    internal Cmd_repo＿rebuild＿old( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "repo rebuild old",
                "Tries to rebuild the oldest releases until a success.\r\nFailing commits are tagged with a '+deprecated' tag.",
                1,
                -1,
                arguments: [
                ],
                options: [
                ],
                flags: [
                    (["--warn-only",], "Warns only: doesn't create a 'deprecated' tag on the failing commit." ),
                    (["--run-test",], "Runs unit tests. They must be successful." ),
                    (["--all",], "Consider all the Repos of the current World (even if current path is in a Repo)." ),
                ],
                "RebuildOldAsync", MethodAsyncReturn.Task ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        var f0 = cmdLine.EatFlag( Flags[0].Names );
        var f1 = cmdLine.EatFlag( Flags[1].Names );
        var f2 = cmdLine.EatFlag( Flags[2].Names );
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return new ValueTask<bool>( ((CKli.Build.Plugin.BuildPlugin)Instance).RebuildOldAsync(
                                           monitor, context, f0, f1, f2 ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_repo＿rebuild＿version : PluginCommand
{
    internal Cmd_repo＿rebuild＿version( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "repo rebuild version",
                "Rebuild the specified version in the current repository.",
                1,
                -1,
                arguments: [
                    ("version", "The version to rebuild."),
                ],
                options: [
                ],
                flags: [
                    (["--skip-tests",], "Don't run tests even if they have never locally run on this commit." ),
                    (["--force-tests",], "Run tests even if they have already run successfully on this commit." ),
                ],
                "RebuildVersionAsync", MethodAsyncReturn.Task ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        var a0 = cmdLine.EatArgument();
        var f0 = cmdLine.EatFlag( Flags[0].Names );
        var f1 = cmdLine.EatFlag( Flags[1].Names );
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return new ValueTask<bool>( ((CKli.Build.Plugin.BuildPlugin)Instance).RebuildVersionAsync(
                                           monitor, context, a0, f0, f1 ) );
    }
}
[GeneratedCode("CKli", "0.0.8--0183-dev")]
sealed class Cmd_migrate＿net8 : PluginCommand
{
    internal Cmd_migrate＿net8( IPluginTypeInfo typeInfo )
        : base( typeInfo,
                "migrate net8",
                "Migrate Net8 stack.",
                -1,
                -1,
                arguments: [
                ],
                options: [
                ],
                flags: [
                    (["--reset-all",], "<no description>" ),
                    (["--check-develop",], "<no description>" ),
                ],
                "Migrate", MethodAsyncReturn.None ) {}
    protected override ValueTask<bool> HandleCommandAsync( IActivityMonitor monitor, CKliEnv context, CommandLineArguments cmdLine )
    {
        var f0 = cmdLine.EatFlag( Flags[0].Names );
        var f1 = cmdLine.EatFlag( Flags[1].Names );
        if( !cmdLine.Close( monitor ) ) return ValueTask.FromResult( false );
        return ValueTask.FromResult( ((CKli.Net8Migration.Plugin.Net8MigrationPlugin)Instance).Migrate(
                                           monitor, f0, f1 ) );
    }
}
