<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CKli.ArtifactHandler.Plugin" Version="$(CKliVersion)" />
    <PackageVersion Include="CKli.BranchModel.Plugin" Version="$(CKliVersion)" />
    <PackageVersion Include="CKli.Build.Plugin" Version="$(CKliVersion)" />
    <PackageVersion Include="CKli.CommonFiles.Plugin" Version="$(CKliVersion)" />
    <PackageVersion Include="CKli.HotZone.Plugin" Version="$(CKliVersion)" />
    <PackageVersion Include="CKli.Migration.Plugin" Version="$(CKliVersion)" />
    <PackageVersion Include="CKli.Publish.Plugin" Version="$(CKliVersion)" />
    <PackageVersion Include="CKli.ShallowSolution.Plugin" Version="$(CKliVersion)" />
    <PackageVersion Include="CKli.VersionTag.Plugin" Version="$(CKliVersion)" />

    <PackageVersion Include="CKli.Plugins.Core" Version="$(CKliVersion)" />
  </ItemGroup>
</Project>
